spring:
  datasource:
    url: jdbc:mysql://47.103.24.126:3306/zhoushan?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/zhoushan?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 8080
#  servlet:
#    context-path: /hello/hello

mypath: /usr/local/tomcat/webapps/start/WEB-INF/classes/static/images/

